version: '3'
volumes:
  elysia-pg-data:
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: elysia
      POSTGRES_PASSWORD: elysia
      POSTGRES_DB: elysia
    volumes:
      - elysia-pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  test-postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5532:5432
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./dev.conf:/etc/nginx/conf.d/default.conf
