apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: multi-tenant-app
  labels:
    app: postgres
    group: multi-tenant-app
data:
  POSTGRES_DB: multi-tenant-db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: someSecurePassword
  PG_URL: postgres://admin:someSecurePassword@postgres.multi-tenant-app.svc.cluster.local:5432/multi-tenant-db
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: multi-tenant-app
  labels:
    type: local
    app: postgres
    group: multi-tenant-app
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/multi-tenant-db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: multi-tenant-app
  labels:
    app: postgres
    group: multi-tenant-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: multi-tenant-app
  labels:
    app: postgres
    group: multi-tenant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: multi-tenant-app
  labels:
    app: postgres
    group: multi-tenant-app
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30030
  selector:
    app: postgres
